rss/urls.py
'''
Created on Nov 2, 2013

@author: shengeng
'''
from django.conf.urls import patterns, url

from .views import *

urlpatterns = patterns('',
    url(r'^refresh_tlquan_news', refresh_tlquan_news, name='refresh_tlquan_news'),
    url(r'^refresh_jiaquan_news', refresh_jiaquan_news, name='refresh_jiaquan_news'),
    url(r'^tlnews/webview/', tlnews_webview, name='tlnews_webview'),
)

ywbserver/urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'ywbserver.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    #url(r'^admin/', include(admin.site.urls)),
    url(r'^$', 'apphome.views.index', name='index'),
    url(r'^index$', 'apphome.views.index', name='index'),
    url(r'^apphome/', include('apphome.urls')),
    url(r'^user/', include('users.urls')),
    url(r'^knowledge/', include('knowledge.urls')),
    #url(r'^appmerchant/', include('merchant.urls')),
    url(r'^appcommercial/', include('commercial.urls')),
    url(r'^merchant/', include('merchant.urls')),
    url(r'^merchant/accounts/', include('registration.backends.default.urls')),
    url(r'^jiaquan/', include('jiaquan.urls')),
    url(r'^tlquan/', include('tlquan.urls')),
    url(r'^photos/', include('photos.urls')),
    url(r'^weather/', include('weather.urls')),
    url(r'^weixin/', include('weixin.urls')),
    url(r'^personality/', include('personality.urls')),
    url(r'^rss/', include('rss.urls')),
    (r'^media/(?P<path>.*)$', 'django.views.static.serve', { 'document_root': settings.MEDIA_ROOT})
    
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

baby/models.py
# -*- coding: UTF-8 -*-
from django.db import models
from django.contrib.auth.models import User
from django.contrib.gis.db import models
from django.contrib.gis.geos import Point, fromstr
from django.contrib.gis.measure import D # alias for Distance
from photos.models import Head

class Baby(models.Model):
    user = models.OneToOneField(User)
    type = models.IntegerField(10,null=True)   ###type = 1: from app, type =2: from weixin
    name = models.TextField(max_length=40,null=True)
    birthday = models.DateField(null=True)
    sex = models.TextField(max_length=10,null=True)
    weight = models.FloatField(2,null=True)
    height = models.FloatField(2,null=True)
    city = models.TextField(max_length=40,null=True)
    homeaddr = models.TextField(max_length=100,null=True)
    schooladdr = models.TextField(max_length=100,null=True)
    homepoint = models.PointField(null=True)
    schoolpoint = models.PointField(null=True)
    mobile = models.TextField(max_length=40,null=True)
    objects = models.GeoManager()

rss/models.py
from django.db import models
import datetime
from django.utils.timezone import utc
from quan.models import *

# Create your models here.
class TLNews(models.Model):
    age = models.FloatField()
    keyword = models.TextField()
    title = models.TextField(unique=True)
    summary = models.TextField(null = True)
    text = models.TextField(null = True)
    piclink = models.TextField(null = True)
    link = models.TextField()
    published_time = models.DateTimeField(default=datetime.datetime.utcnow().replace(tzinfo=utc))
    create_time = models.DateTimeField(default=datetime.datetime.utcnow().replace(tzinfo=utc))


class TLNewsKeyword(models.Model):
    word = models.TextField()
    age = models.FloatField()


class TlNewsComment(CommentBase):
    news = models.ForeignKey(TLNews)


class TlNewsPraise(PraiseBase):
    news = models.ForeignKey(TLNews, related_name="TlNewsPraiseNews")


class TlNewsCollection(models.Model):
    user = models.OneToOneField(User)
    collections = dbarray.IntegerArrayField()


def get_news_byage(age):
    if age == None:
        return None
    newslist = TLNews.objects.filter(age = age).order_by('-published_time')
    if not newslist:
        news =TLNews.objects.all().order_by('-published_time')[0]
    else:
        news =newslist[0]
    return news


def get_news_byids(ids):
    if not ids:
        return None
    news = TLNews.objects.filter(id__in = ids)
    news_list = list(news)
    news_list.sort(key=lambda news: -ids.index(news.id))
    return news_list



class LocalNews(models.Model):
    city = models.TextField()
    keyword = models.TextField()
    title = models.TextField(unique=True)
    summary = models.TextField()
    link = models.TextField()
    published_time = models.DateTimeField(default=datetime.datetime.utcnow().replace(tzinfo=utc))
    create_time = models.DateTimeField(default=datetime.datetime.utcnow().replace(tzinfo=utc))


class LocalNewsKeyword(models.Model):
    word = models.TextField()
    city = models.TextField()


class LocalNewsComment(CommentBase):
    news = models.ForeignKey(LocalNews)


class LocalNewsPraise(PraiseBase):
    news = models.ForeignKey(LocalNews, related_name="LocalNewsPraiseNews")


class LocalNewsCollection(models.Model):
    user = models.OneToOneField(User)
    collections = dbarray.IntegerArrayField()


def get_localnews_bycity(city):
    if city == None:
        return None
    print(city)
    news =LocalNews.objects.filter(city = city).order_by('-published_time')[0]
    return news


def get_localnews_byids(ids):
    if not ids:
        return None
    news = LocalNews.objects.filter(id__in = ids)
    news_list = list(news)
    news_list.sort(key=lambda news: -ids.index(news.id))
    return news_list

templates/shop/shop.html
<html>
<head>
    <meta charset="utf-8">
    <meta name="description" content="">
    <meta name="author" content="">
    <meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1,minimum-scale=1" />
</head>
<body>
<div align="center">
<img src={{pic}}  style="width: 300px; height: 241px, display:inline">
</div>
<span align="center">
<h2>
{{shop_title}}<br/>
</h2>
</span>

<span>
<h3>
商家地址：{{shop_address}}
</h3>
</span>

<span>
<h3>
商家简介：{{shop_content}}
</h3>
<br/></span>

<span>
<h3>
<a href="{{shop_url}}">商家链接</a>
</h3>
</span>
<br></br>
<label>写评论</label>

<form action="http://wjbb.cloudapp.net/shop/addshopcomment/{{shop_shopid}}/" method="post">
<textarea name="shopcomment" cols="40" rows="3"></textarea>
<input type="submit" value="发布" />
<br></br>
<label>评论</label>
<ul>
{% for comment in comments %}
<li>{{comment.comment}}</li>
{% endfor %}
</ul>
</form>

</body>
</html>

templates/shop/shopform.html
<html>
<head>
    <title>Forms</title>
</head>
<body>
    <h1>add shop</h1>
    {% if form.errors %}
        <p style="color: red;">
            Please correct the error{{ form.errors|pluralize }} below.
        </p>
    {% endif %}
    <form name="shopform" action="" method="post" >
    {% csrf_token %}
        <div class="field">
            {{ form.name.errors }}
            <label for="id_name">name:</label>
            {{ form.name }}
        </div>
       <div class="field">
            {{ form.city.errors }}
            <label for="id_city">city:</label>
            {{ form.city }}
        </div>
        <div class="field">
            {{ form.address.errors }}
            <label for="id_address">address:</label>
            {{ form.address }}
        </div>
        <div class="field">
            {{ form.url.errors }}
            <label for="id_url">url:</label>
            {{ form.url }}
        </div>
        <div class="field">
            {{ form.description.errors }}
            <label for="id_description">description:</label>
            {{ form.description }}
        </div>
        <input type="submit" value="Add Shop"/>
    </form>
</body>

</html>